'use strict';

module.exports = {
    bars: {
        BARS_MOUSE_OVER: 'BARS_MOUSE_OVER',
        BARS_MOUSE_OUT: 'BARS_MOUSE_OUT',
        TOP_BARS_BUTTON_CLICK: 'TOP_BARS_BUTTON_CLICK',
        BOTTOM_BARS_PLAY_BUTTON_CLICK: 'BOTTOM_BARS_PLAY_BUTTON_CLICK',
    },

    barsManager: {
        BARS_MANAGER_PLAY_BUTTON_CLICK: 'BARS_MANAGER_PLAY_BUTTON_CLICK',
        BARS_MANAGER_TOP_BUTTON_CLICK: 'BARS_MANAGER_TOP_BUTTON_CLICK',
    },
};